spring:
  datasource:
    url: jdbc:postgresql://localhost/apartmentseller
    username: postgres
    password: root
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false