spring:
  datasource:
    url: jdbc:postgresql://localhost/apartmentseller
    username: postgres
    password: root
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
decoded:
  name: AES
jwt:
  key: jwtKey123456789
  expirationTimeInMS: 864_000_000
auth:
  header:
    name: X-Auth-Token
